version: "3.8"

services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  bezkoder-api:
    depends_on:
      - mysqldb
    image: adeeltech/bezkoder-api:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    environment:
      DB_HOST: mysqldb
      DB_USER: $MYSQLDB_USER
      DB_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      DB_NAME: $MYSQLDB_DATABASE
      DB_PORT: $MYSQLDB_DOCKER_PORT
      CLIENT_ORIGIN: $CLIENT_ORIGIN
    networks:
      - backend
      - frontend

  bezkoder-ui:
    depends_on:
      - bezkoder-api
    image: adeeltech/bezkoder-ui:latest
    expose:
      - "80"
    networks:
      - frontend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bezkoder-ui
      - bezkoder-api
      - grafana
      - prometheus
      - portainer
      - cadvisor
    networks:
      - frontend
      - backend

  prometheus:
    image: prom/prometheus
    restart: always
    expose:
      - "9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: always
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backend

  grafana:
    image: grafana/grafana
    restart: always
    expose:
      - "3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: http://grafana:3000/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    networks:
      - backend

  portainer:
    image: portainer/portainer-ce
    restart: always
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - backend

volumes:
  db:
  grafana_data:
  portainer_data:

networks:
  backend:
  frontend:
