events {}

http {

server {

    listen 80;

    # React UI on root /
    location / {
        proxy_pass http://bezkoder-ui:80;
    }

    # Node API
    location /api/ {
        proxy_pass http://bezkoder-api:8080/;
    }

    # Grafana
    location /grafana/ {
        proxy_pass http://grafana:3000/;
    }

    # Prometheus
    location /prometheus/ {
        proxy_pass http://prometheus:9090/;
    }

    # Portainer
    location /portainer/ {
        proxy_pass http://portainer:9000/;
    }

    # cAdvisor
    location /cadvisor/ {
        proxy_pass http://cadvisor:8080/;
    }

    # Headers for WebSocket / modern apps
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}

}
